# -*- coding: utf-8 -*-
{
    'name': "Quản lý Dự án",
    'version': '1.0.0',
    'category': 'Project',
    'summary': "Hệ thống Quản lý Dự án & Tự động hóa",
    'author': "DNU IT",
    'depends': ['base', 'quan_ly_nhan_su', 'quan_ly_cong_viec', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'data/ai_chat_data.xml',
        'views/du_an_view.xml',
        'views/ai_chat_view.xml',
        'views/quan_ly_menus.xml',
        'views/dashboard_view.xml',
        'views/pitch_deck_template.xml',
        'views/reports.xml',
        'views/cron_job.xml',
        'views/tai_nguyen_view.xml',
        'views/van_de_view.xml',
        'views/milestone_view.xml',
        'views/du_an_line_view.xml',
        'views/ben_lien_quan_view.xml',
        'views/tai_lieu_view.xml',
        'views/kiem_dinh_view.xml',
        'views/risk_view.xml',
        'views/res_config_settings_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'quan_ly_du_an/static/src/css/du_an_style.css',
            'quan_ly_du_an/static/src/css/ai_chat_widget.css',
            'quan_ly_du_an/static/src/js/voice_assistant.js',
            'quan_ly_du_an/static/src/js/ai_chat_widget.js',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}